name: Pull Request

on:
    pull_request:
        branches:
            - master
            - ballerina-1.1.x
            - ballerina-1.2.x

jobs:
    ubuntu-integration-tests:
        name: Integration Tests on Ubuntu
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.head_ref }}-integration-tests
            cancel-in-progress: true
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt'
                    java-version: '11'

    ubuntu-bbe-tests:
        name: BBE Tests on Ubuntu
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.head_ref }}-bbe-tests
            cancel-in-progress: true
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt'
                    java-version: '11'
    windows-build-without-tests:
        name: Windows Build
        runs-on: windows-latest
        concurrency:
            group: ${{ github.head_ref }}-windows
            cancel-in-progress: true
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt'
                    java-version: '11'
